version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    env_file: .env
    depends_on:
      postgres_db:
        condition: service_started
    volumes:
      - ./:/expressive
    ports:
      - '3001:3000'

  postgres_db:
    image: 'postgres:13'
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # make postgres data persist in docker env
