FROM node:lts-slim

ENV TZ=Asia/Jakarta

# User
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -f -r devuser --gid=$GROUP_ID && \
    useradd --create-home -r devuser -g devuser --uid=$USER_ID || true

#add node_modules binary file
ENV NODE_PATH=/node_modules
ENV PATH=${NODE_PATH}/.bin:$PATH

#Sets the working directory for any RUN, CMD, ENTRYPOINT, COPY, and ADD commands
WORKDIR /expressive

#Copy new files or directories into the filesystem of the container
COPY package.json .
COPY yarn.lock .

#Execute commands in a new layer on top of the current image and commit the results
RUN yarn add --dev --ignore-scripts install-peers --modules-folder $NODE_PATH && \
    yarn install --modules-folder $NODE_PATH && \
    yarn cache clean --all

USER $USER_ID:$GROUP_ID

##Copy new files or directories into the filesystem of the container
COPY . .

#Informs container runtime that the container listens on the specified network ports at runtime
EXPOSE 3000

CMD ["npm", "run", "dev"]
